### ISSUE TITLE
运行以后IP地址的还是自己本身的IP

### ISSUE THREAD

**Issue by Gilgamel** [shadowsocks/shadowsocks-nodejs#37]
- -
  在buyvm上架设的OPENVZ上架设的...
  架设的时候一切都显示正常..
  跟着说明修改了IP地址端口等等..
  然后也在本地成功的运行了local.js
  VPS跟本地都显示server listening at port 1110
  但是问题是..在我设置了以后我试着在chrome设置后使用
  然后去看IP..发现依旧是自己原来的IP..并没有改变....
  因为从来没有显示过任何出错提示..所以也不知道问题出在哪里..

**Comment by giftedunicorn** [comment]
因为我用了unblock youku，关掉就好了
